- name: configue user compnent
  hosts: user
  become: yes
  tasks:
  - name: disable default node js 
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable default node js 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs 
    ansible.builtin.dnf: 
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user: 
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
  
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip

  - name: extract user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy user sevice file to  system direcotry
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service 

  - name:  daemon-reload to pick up config changes
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: Enable service 
    ansible.builtin.service:
     name: user
     enabled: yes
     state: started

  